channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - snakemake=3.13.3
  - fastqc=0.11.5
  - samtools=1.4
  - bcftools=1.4
  - trimmomatic=0.36
  - bwa=0.7.15
  - picard=2.9.2
  - gatk=3.5
  - varscan=2.4.2
  - qualimap=2.2
  - sra-tools=2.8.1
  - vardict-java=1.4.10
  - bowtie2=2.3.2
  - yara=0.9.6
  - snpeff=4.3
  - snpsift=4.3
  - freebayes=1.1.0
  - somatic-sniper=1.0.5.0
  - pindel=0.2.5b8
  - bioconductor-deepsnv=1.20.0
  - vardict-java=1.4.10
  - vardict=2017.04.18
